create table tren (
	modelo VARCHAR(50),
	capicidad INT
);
insert into tren (modelo, capicidad) values ('1500', 1);
insert into tren (modelo, capicidad) values ('Freelander', 2);
insert into tren (modelo, capicidad) values ('G-Class', 3);
insert into tren (modelo, capicidad) values ('Canyon', 4);
insert into tren (modelo, capicidad) values ('Summit', 5);
insert into tren (modelo, capicidad) values ('V70', 6);
insert into tren (modelo, capicidad) values ('Freestyle', 7);
insert into tren (modelo, capicidad) values ('3500', 8);
insert into tren (modelo, capicidad) values ('GTO', 9);
insert into tren (modelo, capicidad) values ('Esteem', 10);
insert into tren (modelo, capicidad) values ('LTD', 11);
insert into tren (modelo, capicidad) values ('Grand Caravan', 12);
insert into tren (modelo, capicidad) values ('C-Class', 13);
insert into tren (modelo, capicidad) values ('Ram 1500 Club', 14);
insert into tren (modelo, capicidad) values ('Impala', 15);
insert into tren (modelo, capicidad) values ('S80', 16);
insert into tren (modelo, capicidad) values ('Continental GT', 17);
insert into tren (modelo, capicidad) values ('745', 18);
insert into tren (modelo, capicidad) values ('riolet', 19);
insert into tren (modelo, capicidad) values ('3500 Club Coupe', 20);
insert into tren (modelo, capicidad) values ('LTD Crown Victoria', 21);
insert into tren (modelo, capicidad) values ('B-Series Plus', 22);
insert into tren (modelo, capicidad) values ('2500', 23);
insert into tren (modelo, capicidad) values ('R-Class', 24);
insert into tren (modelo, capicidad) values ('rio', 25);
insert into tren (modelo, capicidad) values ('Rodeo', 26);
insert into tren (modelo, capicidad) values ('G', 27);
insert into tren (modelo, capicidad) values ('Civic', 28);
insert into tren (modelo, capicidad) values ('6000', 29);
insert into tren (modelo, capicidad) values ('E-Series', 30);
insert into tren (modelo, capicidad) values ('Sierra Denali', 31);
insert into tren (modelo, capicidad) values ('RX', 32);
insert into tren (modelo, capicidad) values ('Expedition', 33);
insert into tren (modelo, capicidad) values ('Impreza', 34);
insert into tren (modelo, capicidad) values ('RX', 35);
insert into tren (modelo, capicidad) values ('Eclipse', 36);
insert into tren (modelo, capicidad) values ('QX', 37);
insert into tren (modelo, capicidad) values ('Express 3500', 38);
insert into tren (modelo, capicidad) values ('Caravan', 39);
insert into tren (modelo, capicidad) values ('Quest', 40);
insert into tren (modelo, capicidad) values ('Outback', 41);
insert into tren (modelo, capicidad) values ('Ram Van 2500', 42);
insert into tren (modelo, capicidad) values ('Fairlane', 43);
insert into tren (modelo, capicidad) values ('LR2', 44);
insert into tren (modelo, capicidad) values ('rio', 45);
insert into tren (modelo, capicidad) values ('Voyager', 46);
insert into tren (modelo, capicidad) values ('Savana 1500', 47);
insert into tren (modelo, capicidad) values ('Golf', 48);
insert into tren (modelo, capicidad) values ('Stratus', 49);
insert into tren (modelo, capicidad) values ('Impreza', 50);
insert into tren (modelo, capicidad) values ('Windstar', 51);
insert into tren (modelo, capicidad) values ('LeSabre', 52);
insert into tren (modelo, capicidad) values ('911', 53);
insert into tren (modelo, capicidad) values ('Safari', 54);
insert into tren (modelo, capicidad) values ('S10', 55);
insert into tren (modelo, capicidad) values ('Mazdaspeed 3', 56);
insert into tren (modelo, capicidad) values ('Forester', 57);
insert into tren (modelo, capicidad) values ('Rodeo', 58);
insert into tren (modelo, capicidad) values ('1500 Club Coupe', 59);
insert into tren (modelo, capicidad) values ('Dakota', 60);
insert into tren (modelo, capicidad) values ('Boxster', 61);
insert into tren (modelo, capicidad) values ('Explorer Sport Trac', 62);
insert into tren (modelo, capicidad) values ('Passat', 63);
insert into tren (modelo, capicidad) values ('Villager', 64);
insert into tren (modelo, capicidad) values ('Rally Wagon 3500', 65);
insert into tren (modelo, capicidad) values ('SLK-Class', 66);
insert into tren (modelo, capicidad) values ('Cavalier', 67);
insert into tren (modelo, capicidad) values ('M6', 68);
insert into tren (modelo, capicidad) values ('Rally Wagon G3500', 69);
insert into tren (modelo, capicidad) values ('rio', 70);
insert into tren (modelo, capicidad) values ('R8', 71);
insert into tren (modelo, capicidad) values ('XLR', 72);
insert into tren (modelo, capicidad) values ('Cayman', 73);
insert into tren (modelo, capicidad) values ('900', 74);
insert into tren (modelo, capicidad) values ('Pathfinder', 75);
insert into tren (modelo, capicidad) values ('S40', 76);
insert into tren (modelo, capicidad) values ('6000', 77);
insert into tren (modelo, capicidad) values ('Forenza', 78);
insert into tren (modelo, capicidad) values ('V40', 79);
insert into tren (modelo, capicidad) values ('IS', 80);
insert into tren (modelo, capicidad) values ('Lancer', 81);
insert into tren (modelo, capicidad) values ('Impreza', 82);
insert into tren (modelo, capicidad) values ('Familia', 83);
insert into tren (modelo, capicidad) values ('Wrangler', 84);
insert into tren (modelo, capicidad) values ('RX-7', 85);
insert into tren (modelo, capicidad) values ('Mariner', 86);
insert into tren (modelo, capicidad) values ('SLK-Class', 87);
insert into tren (modelo, capicidad) values ('Mark LT', 88);
insert into tren (modelo, capicidad) values ('Leone', 89);
insert into tren (modelo, capicidad) values ('Rio', 90);
insert into tren (modelo, capicidad) values ('Montero', 91);
insert into tren (modelo, capicidad) values ('Echo', 92);
insert into tren (modelo, capicidad) values ('Riviera', 93);
insert into tren (modelo, capicidad) values ('Explorer', 94);
insert into tren (modelo, capicidad) values ('Crossfire Roadster', 95);
insert into tren (modelo, capicidad) values ('XT', 96);
insert into tren (modelo, capicidad) values ('S70', 97);
insert into tren (modelo, capicidad) values ('Outlander Sport', 98);
insert into tren (modelo, capicidad) values ('Windstar', 99);
insert into tren (modelo, capicidad) values ('Elantra', 100);
