create table estacion (
	nombre VARCHAR(50),
	direccion VARCHAR(50)
);
insert into estacion (nombre, direccion) values ('Stokes-Renner', '8553 Sunnyside Street');
insert into estacion (nombre, direccion) values ('McKenzie, Willms and Sauer', '55 Fairview Park');
insert into estacion (nombre, direccion) values ('Runte, Schaefer and Kihn', '752 Del Sol Parkway');
insert into estacion (nombre, direccion) values ('Lubowitz, Krajcik and Jast', '9626 Sommers Court');
insert into estacion (nombre, direccion) values ('Schuster, Aufderhar and Harvey', '5790 Ohio Trail');
insert into estacion (nombre, direccion) values ('Borer, Labadie and Jast', '05 Pleasure Center');
insert into estacion (nombre, direccion) values ('Sauer-Casper', '3 Karstens Hill');
insert into estacion (nombre, direccion) values ('Cronin-Kemmer', '98 Lerdahl Plaza');
insert into estacion (nombre, direccion) values ('Olson and Sons', '56263 Buhler Junction');
insert into estacion (nombre, direccion) values ('Hammes Inc', '274 Bluejay Parkway');
insert into estacion (nombre, direccion) values ('Streich Group', '63 Loomis Trail');
insert into estacion (nombre, direccion) values ('Reynolds Group', '1257 Ilene Place');
insert into estacion (nombre, direccion) values ('Block-Koepp', '935 Red Cloud Alley');
insert into estacion (nombre, direccion) values ('Kuvalis-Yost', '962 Spohn Terrace');
insert into estacion (nombre, direccion) values ('Murray, Yost and Marvin', '26 Vera Plaza');
insert into estacion (nombre, direccion) values ('Schamberger, Paucek and Jacobson', '13 Transport Park');
insert into estacion (nombre, direccion) values ('Marquardt, Gibson and Corwin', '86136 Buena Vista Way');
insert into estacion (nombre, direccion) values ('Kilback, Franecki and Kub', '1739 Bunting Center');
insert into estacion (nombre, direccion) values ('Orn, Kozey and Durgan', '24313 Sherman Trail');
insert into estacion (nombre, direccion) values ('Smitham, Marvin and Vandervort', '6153 Maple Wood Pass');
insert into estacion (nombre, direccion) values ('Kohler and Sons', '6215 7th Avenue');
insert into estacion (nombre, direccion) values ('Hermann-Quitzon', '47 Rigney Alley');
insert into estacion (nombre, direccion) values ('Kilback, Mohr and Borer', '043 Hagan Way');
insert into estacion (nombre, direccion) values ('Bogisich-Bogan', '75 4th Parkway');
insert into estacion (nombre, direccion) values ('Bailey, Boyer and Collier', '8300 Artisan Park');
insert into estacion (nombre, direccion) values ('Quigley LLC', '8130 Holmberg Alley');
insert into estacion (nombre, direccion) values ('Schimmel, Marquardt and Zieme', '60429 Sage Street');
insert into estacion (nombre, direccion) values ('Rau, Gorczany and Maggio', '33396 Hintze Junction');
insert into estacion (nombre, direccion) values ('Tremblay Group', '569 Hansons Place');
insert into estacion (nombre, direccion) values ('Lemke, Swaniawski and Von', '921 Hayes Place');
insert into estacion (nombre, direccion) values ('Sawayn, Sporer and Weber', '6 Fallview Park');
insert into estacion (nombre, direccion) values ('Ward-Lemke', '7 Michigan Way');
insert into estacion (nombre, direccion) values ('Cummerata and Sons', '01 Morrow Park');
insert into estacion (nombre, direccion) values ('Powlowski-Berge', '503 Debra Alley');
insert into estacion (nombre, direccion) values ('O''Hara-Adams', '48 Linden Avenue');
insert into estacion (nombre, direccion) values ('Thiel-Blick', '44 Stoughton Park');
insert into estacion (nombre, direccion) values ('Johnston Inc', '76 Birchwood Lane');
insert into estacion (nombre, direccion) values ('Davis, Jones and Lindgren', '963 Glendale Center');
insert into estacion (nombre, direccion) values ('Kuhic, Bartoletti and Green', '91 Pankratz Circle');
insert into estacion (nombre, direccion) values ('Bechtelar, Crist and Rowe', '1991 Golden Leaf Junction');
insert into estacion (nombre, direccion) values ('Huels Group', '2 Carey Terrace');
insert into estacion (nombre, direccion) values ('Cruickshank-Rempel', '2 Mcbride Road');
insert into estacion (nombre, direccion) values ('Robel, McKenzie and Johnston', '4377 Summerview Street');
insert into estacion (nombre, direccion) values ('Pfeffer-Funk', '42 Aberg Way');
insert into estacion (nombre, direccion) values ('Goyette, Kovacek and Schmitt', '76 Moose Junction');
insert into estacion (nombre, direccion) values ('Streich, Crona and Kovacek', '34551 Jenna Lane');
insert into estacion (nombre, direccion) values ('Waters, Lueilwitz and Cartwright', '56 Scoville Court');
insert into estacion (nombre, direccion) values ('Reynolds, Abshire and Becker', '6 Namekagon Alley');
insert into estacion (nombre, direccion) values ('Parker Inc', '60 Katie Parkway');
insert into estacion (nombre, direccion) values ('Mayer, Wisozk and Zulauf', '13491 Randy Circle');
insert into estacion (nombre, direccion) values ('Bednar-Welch', '1 Eastlawn Pass');
insert into estacion (nombre, direccion) values ('Dare-Wunsch', '76 Center Place');
insert into estacion (nombre, direccion) values ('Bechtelar, Marks and Bayer', '99 Old Gate Parkway');
insert into estacion (nombre, direccion) values ('Oberbrunner, Gibson and Raynor', '397 New Castle Point');
insert into estacion (nombre, direccion) values ('Grimes and Sons', '1 Petterle Circle');
insert into estacion (nombre, direccion) values ('Huel-Hodkiewicz', '47984 Roxbury Road');
insert into estacion (nombre, direccion) values ('Miller-Stiedemann', '8 Quincy Place');
insert into estacion (nombre, direccion) values ('Bechtelar LLC', '0 Toban Circle');
insert into estacion (nombre, direccion) values ('Connelly-Witting', '54 Buhler Center');
insert into estacion (nombre, direccion) values ('Reilly Group', '623 Farmco Trail');
insert into estacion (nombre, direccion) values ('Fisher Inc', '94 Russell Avenue');
insert into estacion (nombre, direccion) values ('Gaylord and Sons', '60665 Doe Crossing Park');
insert into estacion (nombre, direccion) values ('Murazik-Lueilwitz', '4 Anzinger Alley');
insert into estacion (nombre, direccion) values ('Schowalter, Schinner and Kuvalis', '84944 Loeprich Avenue');
insert into estacion (nombre, direccion) values ('Koch LLC', '36 Eastwood Pass');
insert into estacion (nombre, direccion) values ('Pfannerstill LLC', '245 Sunbrook Place');
insert into estacion (nombre, direccion) values ('Balistreri-Waelchi', '5 Onsgard Court');
insert into estacion (nombre, direccion) values ('Harris, Hermann and Kovacek', '35926 Eagle Crest Point');
insert into estacion (nombre, direccion) values ('Keebler, Padberg and Dibbert', '7 Mcbride Way');
insert into estacion (nombre, direccion) values ('Kshlerin-Moen', '52060 Weeping Birch Street');
insert into estacion (nombre, direccion) values ('Kuphal-Grimes', '79709 Oak Valley Court');
insert into estacion (nombre, direccion) values ('Hayes-Kunde', '8139 Glendale Way');
insert into estacion (nombre, direccion) values ('Goyette Group', '400 Weeping Birch Parkway');
insert into estacion (nombre, direccion) values ('Greenfelder-Paucek', '79944 Green Avenue');
insert into estacion (nombre, direccion) values ('O''Reilly Inc', '77073 Bowman Trail');
insert into estacion (nombre, direccion) values ('Gottlieb-Welch', '1468 Delaware Drive');
insert into estacion (nombre, direccion) values ('Hane, Kiehn and Mraz', '85908 Springs Avenue');
insert into estacion (nombre, direccion) values ('Reichel-Stiedemann', '5952 American Avenue');
insert into estacion (nombre, direccion) values ('Ernser, Homenick and Spinka', '3 Sunnyside Street');
insert into estacion (nombre, direccion) values ('Keeling-McDermott', '942 Oriole Alley');
insert into estacion (nombre, direccion) values ('Roberts, Koch and Cassin', '4 Dryden Alley');
insert into estacion (nombre, direccion) values ('Kemmer-Welch', '7708 Eagle Crest Court');
insert into estacion (nombre, direccion) values ('Parisian Group', '7 Crownhardt Crossing');
insert into estacion (nombre, direccion) values ('Willms Group', '03039 Garrison Junction');
insert into estacion (nombre, direccion) values ('Howe-Boyle', '5 Loeprich Way');
insert into estacion (nombre, direccion) values ('Jerde-Hills', '5 Dunning Road');
insert into estacion (nombre, direccion) values ('Aufderhar LLC', '5768 David Drive');
insert into estacion (nombre, direccion) values ('Streich-Grimes', '96908 Victoria Street');
insert into estacion (nombre, direccion) values ('Davis-Harber', '5 Erie Road');
insert into estacion (nombre, direccion) values ('Satterfield Group', '802 Bunting Drive');
insert into estacion (nombre, direccion) values ('Murray LLC', '843 Dahle Center');
insert into estacion (nombre, direccion) values ('Hickle Group', '8165 Surrey Parkway');
insert into estacion (nombre, direccion) values ('Luettgen, Gaylord and Kshlerin', '24 South Avenue');
insert into estacion (nombre, direccion) values ('Wilkinson Group', '91636 Hagan Circle');
insert into estacion (nombre, direccion) values ('Monahan-Mueller', '9 Ruskin Hill');
insert into estacion (nombre, direccion) values ('Runolfsson-Runolfsson', '714 Meadow Ridge Pass');
insert into estacion (nombre, direccion) values ('Cole and Sons', '853 Pierstorff Way');
insert into estacion (nombre, direccion) values ('Maggio-Grimes', '6 3rd Pass');
insert into estacion (nombre, direccion) values ('Crona, Kovacek and Rolfson', '705 Bluejay Point');
insert into estacion (nombre, direccion) values ('Orn, Mueller and Runolfsson', '5 Luster Street');
